Jawaban No 2

INSERT INTO mahasiswa(nim,nama,tgl_lhr) 
VALUES(20210801205,"Bagus Abyyu Azhar","01/01/17"),
	  (20210801208,"Ageng","05/11/05"),
	  (20210801203,"marsha","01/08/21")
;			
INSERT INTO dosen(kd_dosen,nama,email)  
VALUES(723823,"pak Jefry","jf@gmail.com"),
	  (574332,"pak yono","sb@gmail.com"),
	  (857273,"pak yuli","yn@gmail.com")
;
INSERT INTO mata_kuliah(matkul)  
VALUES("PBO"),
	  ("Kalkulus"),
	  ("Sistem Operasi")
;
